### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by michal-bootcamp** [JoannaKu/Nowe-repozytorium#1]
Dodalem pare zmian od siebie. Do zrobienia:
- [ ] pobierz zmiany ze zdalnego repo
- [ ] domerguj u siebie lokalnie branch `test` do brancha `master`
- [ ] zmien nazwe pliku html na `index.html` (tak nazwany plik jest domyslnie wyswietlany na stronie internetowej) i zakomituj te zmiane nazwy
- [ ] wyslij wszystkie zmiany na zdalne repozytorium (na githuba)

**Comment by JoannaKu** [comment]
coś chyba strasznie namieszałam przy tym zadaniu i dziwne rzeczy mi się pokazują w terminalu...

**Comment by michal-bootcamp** [comment]
tak, zrobilas cos dziwnego, ale co pokazuje terminal jak wpiszesz `git status`?

powinnas teraz domergowac test do mastera, czyli bedac na branchu master, odpalic
`git merge test`

potem zmien nazwe pliku html, zakomituj i wypuszuj

**Comment by JoannaKu** [comment]
Nie wiem czy udało mi się zrobić wszystko co powinnam. Na pewno nie działa mi dodatek grunt-contrib-watch. Trochę jest to dla mnie skomplikowany temat i nie do końca rozumiem co robię...

**Comment by michal-bootcamp** [comment]
Zadanie z gruntem zrob w osobnym repo i tam bedziemy z nim dzialac. To repozytorium zostawmy sobie do wstepnych prob z gitem
